### ISSUE TITLE
It is just me?

### ISSUE THREAD

**Issue by manaskhandelwal** [benawad/astralfans-landing#7]
The designer copied (sort of) the logo from here 🙄. 
👉 [**https://dribbble.com/shots/14509974-astro**](https://dribbble.com/shots/14509974-astro)

**Comment by DheerajMahra** [comment]
@manaskhandelwal Lol. Color palette and sequence of colors are also same 😹

**Comment by vitorgouveia** [comment]
Ben should take a look at this

**Comment by redpwilliams** [comment]
I can already hear the question "How much did you pay for this design" come into play

**Comment by ShapeShapa** [comment]
hah it has the same colour palette

**Comment by vitorgouveia** [comment]
> hah it has the same colour palette

i think the designer just ripped of this logo and delivered from ben, it makes sense since the figma design look generic also

**Comment by timthedev07** [comment]
LOL just realized.

**Comment by alator21** [comment]
Who is here after AstralLogs[1] ?

**Comment by condinoaljoseph** [comment]
> Who is here after AstralLogs[1] ?

:hand:

**Comment by Rizialdi** [comment]
> Who is here after AstralLogs[1] ?

✋

**Comment by timthedev07** [comment]
Did you guys see Ben's latest video?

Here is the [link](https://youtu.be/6HvcW6eX3HE)

**Comment by rosman83** [comment]
I made a new logo that we could possibly use as a replacement. Find the SVG for the full size version here since github wouldn't let me upload. https://cutt.ly/HmJinzp

**Comment by logark12** [comment]
> Who is here after AstralLogs[1] ?

✋

**Comment by manaskhandelwal** [comment]
![lol](https://media1.tenor.com/images/27a1c29c08cbdf3b1861c5846c35619a/tenor.gif?itemid=15913430)
